version: "3.9"

services:
  details_app:
    image: thebluedrara/details_app:1
    container_name: details_app
    ports:
      - 5000:5000

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - 8080:80
    volumes:
      - ../config/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - details_app
