apiVersion: v1
kind: Service
metadata:
  name: details-app-service
spec:
  selector:
    app: details-app
  ports:
    - name: http
      port: 5000
      targetPort: 5000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: NodePort

